/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.reading.model.impl;

import com.liferay.reading.model.Book;
import com.liferay.reading.service.BookLocalServiceUtil;

/**
 * The extended model base implementation for the Book service. Represents a row in the &quot;Reading_Book&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BookImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BookImpl
 * @see Book
 * @generated
 */
public abstract class BookBaseImpl extends BookModelImpl implements Book {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a book model instance should use the <code>Book</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			BookLocalServiceUtil.addBook(this);
		}
		else {
			BookLocalServiceUtil.updateBook(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-765565525