#
# This is a generated file.
#

api.version=v1.0
batch.engine.entity.class.name=com.liferay.learning.rest.dto.v1_0.Book
batch.engine.task.item.delegate=true
batch.planner.export.enabled=true
batch.planner.import.enabled=false
crud.entity.class.name=com.liferay.learning.rest.dto.v1_0.Book
crud.item.delegate=true
entity.class.name=com.liferay.learning.rest.dto.v1_0.Book
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Learning.REST)
osgi.jaxrs.resource=true