components:
    schemas:
        Book:
            description: "Represents a book."
            properties:
                author:
                    description: "The author of the book."
                    type: string
                id:
                    description: "The book's ID."
                    format: int64
                    readOnly: true
                    type: integer
                isbn:
                    description: "The book's ISBN."
                    type: string
                title:
                    description: "The title of the book."
                    type: string
            required:
                - "title"
            type: object
info:
    description:
        "Headless API for reading books.. A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.learning.rest.client', and version '1.0.0'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Learning"
    version: v1.0
openapi: 3.0.1
paths:
    "/books":
        get:
            description: "Retrieves the books. Results can be paginated."
            operationId: getBooksPage
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Book"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Book"
                                type: array
                    description: ""
            tags: ["Book"]
    "/books/{bookId}":
        get:
            description: "Retrieves the book via its ID."
            operationId: getBook
            parameters:
                - in: path
                  name: bookId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Book"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Book"
                    description: ""
            tags: ["Book"]